# This is a basic workflow to help you get started with Actions
#name: BootCamp 2020 Project

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      - name: Install Surge
        run: npm install -g surge
      - name: Run surge
        run: surge ./ salahbootcamp2020website.surge.sh --token ${{ secrets.SURGE_TOKEN_Key }}
